name: Build Android App

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"

      - name: Get Packages
        run: flutter pub get

      # 🔹 Build APK
      - name: Build APK
        run: flutter build apk --flavor dev -t lib/main.dart --release

      # 🔹 Build AAB (Play Store)
      #- name: Build AAB
      #  run: flutter build appbundle

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: apk-release
          path: build/app/outputs/flutter-apk/app-release.apk

      #- name: Upload AAB
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: aab-release
      #    path: build/app/outputs/bundle/release/app-release.aab