name: Web Dev to Firebase

on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.41.4"

      - name: Get Packages
        run: flutter pub get

      - name: Build Web
        run: flutter build web -t lib/main_dev.dart

      - name: Upload Web Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: flutter-web-build
          path: build/web

      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.SECRET_AUTH_DEV }}
          projectId: mulialand-dev
          channelId: live